FROM fedora:latest

RUN dnf install -y \
        python3 \
        python3-pip \
        python3-devel \
        portaudio-devel \
        libnotify \
        wtype \
        xdotool \
        espeak-ng \
        git \
        gcc \
        make \
    && dnf clean all

WORKDIR /app
COPY . .

RUN python3 -m venv venv && \
    venv/bin/pip install --upgrade pip setuptools && \
    venv/bin/pip install -e ".[dev]"

CMD ["venv/bin/python", "-m", "pytest", "tests/", "-v", "-m", "not slow"]
