FROM archlinux:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
        base-devel \
        python \
        python-pip \
        portaudio \
        wtype \
        xdotool \
        git

WORKDIR /app
COPY . .

RUN python -m venv venv && \
    venv/bin/pip install --upgrade pip setuptools && \
    venv/bin/pip install -e ".[dev]"

CMD ["venv/bin/python", "-m", "pytest", "tests/", "-v", "-m", "not slow"]
